// <auto-generated />
namespace MasAresei.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RemovingIngredientEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovingIngredientEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "202110281738441_RemovingIngredientEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
